version: '2'

services:
  redis:
    image: redis

  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_USER:sentry
      - POSTGRES_PASSWORD:sentry
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  sentry:
    image: sentry:8
    depends_on:
      - "postgres"
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: redis
    links:
     - redis
     - postgres
    ports:
     - 127.0.0.1:8000:8000
    stdin_open: true
    tty: true

  sentry_celery_beat:
    image: sentry:8
    depends_on:
     - redis
     - postgres
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: redis

  sentry_celery_worker:
    image: sentry:8
    depends_on:
     - redis
     - postgres
    command: "sentry run worker"
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: redis
