version: '2'

services:
  redis:
    image: redis

  postgres:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  sentry:
    image: sentry:9
    depends_on:
      - "postgres"
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: ${POSTGRES_USER}
      SENTRY_DB_PASSWORD: ${POSTGRES_PASSWORD}
      SENTRY_REDIS_HOST: redis
    env_file:
      - .env
    links:
     - redis
     - postgres
    #  - mailserver
    ports:
     - 127.0.0.1:9000:9000
    stdin_open: true
    tty: true

  sentry_celery_beat:
    image: sentry:9
    depends_on:
     - redis
     - postgres
    #  - mailserver
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: ${POSTGRES_USER}
      SENTRY_DB_PASSWORD: ${POSTGRES_PASSWORD}
      SENTRY_REDIS_HOST: redis
    env_file:
      - .env

  sentry_celery_worker:
    image: sentry:9
    depends_on:
     - redis
     - postgres
    #  - mailserver
    command: "sentry run worker"
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: ${POSTGRES_USER}
      SENTRY_DB_PASSWORD: ${POSTGRES_PASSWORD}
      SENTRY_REDIS_HOST: redis
    env_file:
      - .env
# ? disabled because right now self-hosted emails are blocked or going to spam
  # mailserver:
  #   image: namshi/smtp
  #   env_file:
  #     - .env
