- stat: path=/www/sentry/.env
  register: check_swap_file

- include: swap.yml
  when: check_swap_file.stat.exists == False

- include: nginx.yml

- include: docker.yml

- include: sentry.yml

- include: letsencrypt.yml
