- name: install nginx
  apt: package=nginx update_cache=yes

- name: Nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-enabled/sentry.conf
  notify: restart nginx

- name: Disable the default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

# - htpasswd:
#     path: /etc/nginx/.htpasswd
#     name: "{{ nginx_user }}"
#     password: "{{ nginx_password }}"
#     owner: root
#     group: www-data
#     mode: 0640
